### ISSUE TITLE
sumo checksum bug

### ISSUE THREAD

**Issue by eugenevinitsky** [flow-project/flow#177]
When we close a traci_connection we get the following error:
sumo(81446,0x7fff90b42340) malloc: *** error for object 0x7fe935609cc0: incorrect checksum for freed object - object was probably modified after being freed.

This is probably horrifying to users; we should try to remove it

**Comment by eugenevinitsky** [comment]
@AboudyKreidieh mahesh has pointed out that this is going to occur every time there's a keyboard interrupt. It doesn't seem like there's a clean way to catch this; do you have any thoughts?

**Comment by eugenevinitsky** [comment]
Note, this is resolved by upgrading sumo.

**Comment by Proyash56952** [comment]
Hi! I am using the upgraded SUMO (version 1.6), but still facing this issue. Is there any solve for this?
